# NumPy Basics

NumPy is the backbone of numerical computing in Machine Learning.

### Topics Covered
- Arrays
- Vectorized Operations
- Broadcasting
- Indexing & Slicing
- Linear Algebra


# Import & Arrays

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr


array([1, 2, 3, 4])

# Array Shapes

In [2]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

matrix.shape


(3, 2)

# Zeros, Ones, Random

In [3]:
np.zeros((3, 3)), np.ones((2, 2)), np.random.rand(3)


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.]]),
 array([0.89802787, 0.05335328, 0.17942217]))

# Vectorized Ops

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y, x * y


(array([5, 7, 9]), array([ 4, 10, 18]))

# Broadcasting

In [5]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data + 10


array([[11, 12, 13],
       [14, 15, 16]])

# Indexing & Slicing

In [7]:
data[0]
data[:, 1]


array([2, 5])

# Linear Algebra

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np.dot(A, B)


array([[19, 22],
       [43, 50]])